SKILL_CATEGORIES = {
    "Programming Languages": {
        "Python": ["python", "py"],
        "Java": ["java", "core java", "advanced java"],
        "C": ["c"],
        "C++": ["c++", "cpp", "c plus plus"],
        "C#": ["c#", "c sharp", "csharp"],
        "JavaScript": ["javascript", "js", "vanilla js"],
        "TypeScript": ["typescript", "ts"],
        "Go": ["go", "golang"],
        "Rust": ["rust"],
        "Kotlin": ["kotlin"],
        "Swift": ["swift"],
        "PHP": ["php"],
        "Ruby": ["ruby"],
        "Scala": ["scala"],
        "R": ["r", "r language"],
        "MATLAB": ["matlab"],
        "Dart": ["dart"],
        "Perl": ["perl"],
        "Lua": ["lua"],
        "SQL": ["sql"],
        "NoSQL": ["nosql"],
        "Bash": ["bash", "bash scripting"],
        "Shell": ["shell", "shell scripting"]
    },
    "Web Dev": {
        "HTML": ["html", "html5"],
        "CSS": ["css", "css3"],
        "Bootstrap": ["bootstrap"],
        "Tailwind": ["tailwind", "tailwindcss", "tailwind css"],
        "React": ["react", "react.js", "reactjs"],
        "Next.js": ["next.js", "nextjs", "next js"],
        "Angular": ["angular", "angularjs", "angular.js"],
        "Vue.js": ["vue", "vue.js", "vuejs"],
        "Node.js": ["node", "node.js", "nodejs"],
        "Express.js": ["express", "express.js", "expressjs"],
        "Django": ["django"],
        "Flask": ["flask"],
        "FastAPI": ["fastapi", "fast api"],
        "Spring Boot": ["spring boot", "springboot", "spring-boot"],
        "ASP.NET": ["asp.net", "asp net", "dotnet"],
        "Laravel": ["laravel"],
        "WordPress": ["wordpress", "wp"]
    },
    "Databases": {
        "MySQL": ["mysql"],
        "PostgreSQL": ["postgresql", "postgres"],
        "SQLite": ["sqlite"],
        "MongoDB": ["mongodb", "mongo"],
        "Redis": ["redis"],
        "Oracle": ["oracle", "oracle db"],
        "Firebase": ["firebase"],
        "Supabase": ["supabase"],
        "MariaDB": ["mariadb"],
        "SQL Server": ["sql server", "mssql", "ms sql"]
    },
    "AI/ML": {
        "Machine Learning": ["machine learning", "ml"],
        "Deep Learning": ["deep learning", "dl"],
        "TensorFlow": ["tensorflow", "tf"],
        "PyTorch": ["pytorch", "torch"],
        "Scikit-learn": ["scikit-learn", "sklearn", "scikit learn"],
        "OpenCV": ["opencv", "cv2"],
        "NLP": ["nlp", "natural language processing"],
        "LLM": ["llm", "large language model", "large language models"],
        "LangChain": ["langchain"],
        "HuggingFace": ["huggingface", "hugging face"],
        "Computer Vision": ["computer vision", "cv"],
        "Generative AI": ["generative ai", "genai", "gen ai"],
        "Prompt Engineering": ["prompt engineering"],
        "RAG": ["rag", "retrieval augmented generation"],
        "Vector Databases": ["vector database", "vector db", "milvus", "pinecone", "weaviate", "qdrant"],
        "Whisper": ["whisper", "openai whisper"]
    },
    "Cloud/DevOps": {
        "AWS": ["aws", "amazon web services"],
        "Azure": ["azure", "microsoft azure"],
        "GCP": ["gcp", "google cloud platform", "google cloud"],
        "Docker": ["docker"],
        "Kubernetes": ["kubernetes", "k8s"],
        "Linux": ["linux", "ubuntu", "centos", "debian"],
        "Git": ["git"],
        "GitHub": ["github"],
        "GitHub Actions": ["github actions"],
        "Jenkins": ["jenkins"],
        "CI/CD": ["ci/cd", "ci-cd", "ci cd", "continuous integration", "continuous deployment"],
        "Terraform": ["terraform"],
        "Ansible": ["ansible"],
        "Nginx": ["nginx"],
        "Apache": ["apache", "apache2"]
    },
    "Mobile": {
        "Android": ["android", "android development"],
        "Flutter": ["flutter"],
        "React Native": ["react native", "react-native"],
        "Jetpack Compose": ["jetpack compose", "compose"]
    },
    "Data": {
        "Pandas": ["pandas"],
        "NumPy": ["numpy"],
        "Matplotlib": ["matplotlib"],
        "Power BI": ["power bi", "powerbi"],
        "Tableau": ["tableau"],
        "Excel": ["excel", "ms excel"],
        "Spark": ["spark", "apache spark"],
        "Hadoop": ["hadoop", "apache hadoop"]
    },
    "Security": {
        "Network Security": ["network security"],
        "Pen Testing": ["pen testing", "penetration testing", "pentesting"],
        "Ethical Hacking": ["ethical hacking"],
        "Nmap": ["nmap"],
        "Wireshark": ["wireshark"],
        "Burp Suite": ["burp suite", "burpsuite"],
        "Metasploit": ["metasploit"],
        "OWASP": ["owasp"]
    },
    "Other": {
        "REST API": ["rest api", "rest", "restful api"],
        "GraphQL": ["graphql"],
        "Microservices": ["microservices", "micro services"],
        "OOP": ["oop", "object oriented programming", "oops"],
        "DSA": ["dsa", "data structures", "algorithms", "data structures and algorithms"],
        "OS": ["os", "operating system", "operating systems"],
        "Computer Networks": ["computer networks", "cn", "networking"],
        "DBMS": ["dbms", "database management system"],
        "Software Testing": ["software testing", "testing"],
        "Selenium": ["selenium"],
        "JUnit": ["junit"],
        "Postman": ["postman"],
        "Figma": ["figma"],
        "UI/UX": ["ui/ux", "ui ux", "user interface", "user experience"]
    }
}
